from .DB import *


# fetchall_exp:
sql = '''SELECT EXPERIMENTOS.ID, PICTURES.PICTURE, EXPERIMENTOS.FREQ, EXPERIMENTOS.COMPRIMENTO, EXPERIMENTOS.MASSA, EXPERIMENTOS.DENSIDADE, EXPERIMENTOS.TIPO_EXP FROM EXPERIMENTOS INNER JOIN PICTURES ON (EXPERIMENTOS.PIC_ID = PICTURES.ID);'''

# fetchall_exp_sup:
sql = '''SELECT EXPERIMENTOS.ID, PICTURES.PICTURE, EXPERIMENTOS.FREQ, EXPERIMENTOS.COMPRIMENTO, EXPERIMENTOS.MASSA, EXPERIMENTOS.DENSIDADE, EXPERIMENTOS.TIPO_EXP FROM EXPERIMENTOS INNER JOIN PICTURES ON (EXPERIMENTOS.PIC_ID = PICTURES.ID) WHERE EXPERIMENTOS.TIPO_EXP = 'SUP' OR EXPERIMENTOS.TIPO_EXP = 'SUP_APR';'''

# fetchall_exp_corda:
sql = '''SELECT EXPERIMENTOS.ID, PICTURES.PICTURE, EXPERIMENTOS.FREQ, EXPERIMENTOS.COMPRIMENTO, EXPERIMENTOS.MASSA, EXPERIMENTOS.DENSIDADE, EXPERIMENTOS.TIPO_EXP FROM EXPERIMENTOS INNER JOIN PICTURES ON (EXPERIMENTOS.PIC_ID = PICTURES.ID) WHERE EXPERIMENTOS.TIPO_EXP = 'CORDA';'''